# Generated by Django 5.2.6 on 2025-09-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mal_id', models.IntegerField(unique=True)),
                ('image_url', models.URLField()),
                ('synopsis', models.TextField()),
            ],
        ),
    ]
